import React, { useState, useEffect } from "react";
import { careerApi } from "../../api/careerApi";
import { motion } from "framer-motion";
import {
  Box,
  Typography,
  Card,
  CardContent,
  CircularProgress,
  Grid,
  Button,
} from "@mui/material";
import TimelineIcon from "@mui/icons-material/Timeline";
import WorkspacePremiumIcon from "@mui/icons-material/WorkspacePremium";
import WorkIcon from "@mui/icons-material/Work";
import LibraryBooksIcon from "@mui/icons-material/LibraryBooks";
import SchoolIcon from "@mui/icons-material/School";

export const CareerGuidancePage = () => {
  const [recommendations, setRecommendations] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchRecommendations = async () => {
    try {
      setLoading(true);
      setError("");
      const response = await careerApi.getRecommendations();
      if (response.success && response.data) {
        setRecommendations(response.data);
      }
    } catch (err) {
      setError(err.message || "Failed to load career progression advisor details.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  if (loading) {
    return (
      <Box className="flex justify-center items-center h-[60vh]">
        <CircularProgress color="primary" />
      </Box>
    );
  }

  if (error) {
    return (
      <Box className="p-6 text-center">
        <Typography color="error" className="mb-4">
          {error}
        </Typography>
        <Button variant="outlined" onClick={fetchRecommendations}>
          Retry loading
        </Button>
      </Box>
    );
  }

  const {
    recommendedJobRoles = "",
    certifications = "",
    learningRoadmap = "",
    placementPreparationStrategy = "",
  } = recommendations || {};

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <Typography variant="h4" className="font-bold text-slate-100 font-sans" sx={{ fontFamily: "Outfit, Inter, sans-serif" }}>
          AI Career Advisor
        </Typography>
        <Typography variant="body2" className="text-slate-400 mt-1">
          Personalized career guidance and skill path tracking generated by AI based on your resume and interview performance
        </Typography>
      </div>

      <Grid container spacing={4}>
        {/* Recommended Roles */}
        <Grid item xs={12} md={6}>
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <Card className="glass-card h-full border border-white/5">
              <CardContent className="p-6 space-y-4">
                <div className="flex items-center gap-3 border-b border-white/5 pb-3">
                  <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                    <WorkIcon />
                  </div>
                  <Typography variant="h6" className="font-bold text-slate-200 font-sans" sx={{ fontFamily: "Outfit, Inter, sans-serif" }}>
                    Recommended Job Roles
                  </Typography>
                </div>
                <Typography variant="body2" className="text-slate-300 leading-relaxed whitespace-pre-line bg-slate-950/20 p-4 rounded-xl border border-white/5">
                  {recommendedJobRoles || "No role recommendations generated yet. Practice more interviews to populate."}
                </Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>

        {/* Suggested Certifications */}
        <Grid item xs={12} md={6}>
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <Card className="glass-card h-full border border-white/5">
              <CardContent className="p-6 space-y-4">
                <div className="flex items-center gap-3 border-b border-white/5 pb-3">
                  <div className="w-10 h-10 rounded-xl bg-secondary/10 flex items-center justify-center text-secondary">
                    <WorkspacePremiumIcon />
                  </div>
                  <Typography variant="h6" className="font-bold text-slate-200 font-sans" sx={{ fontFamily: "Outfit, Inter, sans-serif" }}>
                    Industry Certifications
                  </Typography>
                </div>
                <Typography variant="body2" className="text-slate-300 leading-relaxed whitespace-pre-line bg-slate-950/20 p-4 rounded-xl border border-white/5">
                  {certifications || "No recommended certifications found."}
                </Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>

        {/* Learning Roadmap */}
        <Grid item xs={12}>
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
            <Card className="glass-card border border-white/5">
              <CardContent className="p-6 space-y-4">
                <div className="flex items-center gap-3 border-b border-white/5 pb-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                    <LibraryBooksIcon />
                  </div>
                  <Typography variant="h6" className="font-bold text-slate-200 font-sans" sx={{ fontFamily: "Outfit, Inter, sans-serif" }}>
                    Skills Learning Roadmap
                  </Typography>
                </div>
                <Typography variant="body2" className="text-slate-300 leading-relaxed whitespace-pre-line bg-slate-950/20 p-4 rounded-xl border border-white/5">
                  {learningRoadmap || "No roadmap available."}
                </Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>

        {/* Placement Strategy */}
        <Grid item xs={12}>
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
            <Card className="glass-card border border-white/5">
              <CardContent className="p-6 space-y-4">
                <div className="flex items-center gap-3 border-b border-white/5 pb-3">
                  <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-400">
                    <SchoolIcon />
                  </div>
                  <Typography variant="h6" className="font-bold text-slate-200 font-sans" sx={{ fontFamily: "Outfit, Inter, sans-serif" }}>
                    Placement Preparation Plan
                  </Typography>
                </div>
                <Typography variant="body2" className="text-slate-300 leading-relaxed whitespace-pre-line bg-slate-950/20 p-4 rounded-xl border border-white/5">
                  {placementPreparationStrategy || "No placement prep strategy currently outlined."}
                </Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>
      </Grid>
    </div>
  );
};
